### ISSUE TITLE
Add a sample compose file

### ISSUE THREAD

**Issue by clockwinder** [Teunwrmzijnallenamenalingebruik/virtualTableTop-Docker#1]
I found your new image on dockerhub, and was curious to spin it up for a test, but I didn't see a sample run/compose for how to easily get it up and running.

It would be great if you added an example so folks like me could easily test out your image!

**Comment by Teunwrmzijnallenamenalingebruik** [comment]
I've added a compose file to the readme on here and on Dockerhub. I didn't add it before as it was mostly something for myself I didn't think to add it before.
